[aws]
disabled = true

[battery]
disabled = true

[character]
success_symbol = "[❯](bold blue)"

[git_branch]
symbol = " "

[git_status]
disabled = true

[jobs]
disabled = true

[status]
format = "[($status)]($style)"
disabled = false
