name: CI
on:
  push:
    branches:
      - master
jobs:
  build:
    name: CI
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Clean Workspace
        run: rm ~/.bash_profile ~/.bashrc
      - name: Run Bootstrap Script
        working-directory: ~
        run: ./bootstrap.sh
