name: CI
on:
  push:
    branches:
      - master
jobs:
  build:
    name: CI
    runs-on: macos-latest
    steps:
      - name: Run Bootstrap Script
        run: curl -s https://raw.githubusercontent.com/jawang35/.dotfiles/master/bootstrap.sh | bash
