name: CI
on:
  push:
    branches:
      - master
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: Clean Workspace
        run: rm -f ~/.bash_profile ~/.bashrc ~/.gitconfig
      - name: Clean Homebrew Packages
        run: brew bundle --file="${HOME}/.config/Brewfile" cleanup --force
        if: matrix.os == 'macos-latest'
      - name: Run Bootstrap Script
        run: ./bootstrap.sh
